package com.example.demo.domain;

public class Demo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.demo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.demo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.demo.id
     *
     * @return the value of public.demo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.demo.id
     *
     * @param id the value for public.demo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.demo.name
     *
     * @return the value of public.demo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.demo.name
     *
     * @param name the value for public.demo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }
}