spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver

flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
    schemas: PUBLIC
    user: postgres
    password: root
    locations: db/migration

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        demo:
          structure: 
            mapper: DEBUG