-- regions
INSERT INTO regions (name) VALUES ('北海道・東北');
INSERT INTO regions (name) VALUES ('関東');
INSERT INTO regions (name) VALUES ('信越・北陸');
INSERT INTO regions (name) VALUES ('東海');
INSERT INTO regions (name) VALUES ('近畿');
INSERT INTO regions (name) VALUES ('中国');
INSERT INTO regions (name) VALUES ('四国');
INSERT INTO regions (name) VALUES ('九州・沖縄');
-- prefectures
INSERT INTO prefectures (region_id, name) VALUES (1,'北海道');
INSERT INTO prefectures (region_id, name) VALUES (1,'青森県');
INSERT INTO prefectures (region_id, name) VALUES (1,'岩手県');
INSERT INTO prefectures (region_id, name) VALUES (1,'宮城県');
INSERT INTO prefectures (region_id, name) VALUES (1,'秋田県');
INSERT INTO prefectures (region_id, name) VALUES (1,'山形県');
INSERT INTO prefectures (region_id, name) VALUES (1,'福島県');
INSERT INTO prefectures (region_id, name) VALUES (2,'茨城県');
INSERT INTO prefectures (region_id, name) VALUES (2,'栃木県');
INSERT INTO prefectures (region_id, name) VALUES (2,'群馬県');
INSERT INTO prefectures (region_id, name) VALUES (2,'埼玉県');
INSERT INTO prefectures (region_id, name) VALUES (2,'千葉県');
INSERT INTO prefectures (region_id, name) VALUES (2,'東京都');
INSERT INTO prefectures (region_id, name) VALUES (2,'神奈川県');
INSERT INTO prefectures (region_id, name) VALUES (3,'新潟県');
INSERT INTO prefectures (region_id, name) VALUES (3,'富山県');
INSERT INTO prefectures (region_id, name) VALUES (3,'石川県');
INSERT INTO prefectures (region_id, name) VALUES (3,'福井県');
INSERT INTO prefectures (region_id, name) VALUES (3,'山梨県');
INSERT INTO prefectures (region_id, name) VALUES (3,'長野県');
INSERT INTO prefectures (region_id, name) VALUES (4,'岐阜県');
INSERT INTO prefectures (region_id, name) VALUES (4,'静岡県');
INSERT INTO prefectures (region_id, name) VALUES (4,'愛知県');
INSERT INTO prefectures (region_id, name) VALUES (4,'三重県');
INSERT INTO prefectures (region_id, name) VALUES (5,'滋賀県');
INSERT INTO prefectures (region_id, name) VALUES (5,'京都府');
INSERT INTO prefectures (region_id, name) VALUES (5,'大阪府');
INSERT INTO prefectures (region_id, name) VALUES (5,'兵庫県');
INSERT INTO prefectures (region_id, name) VALUES (5,'奈良県');
INSERT INTO prefectures (region_id, name) VALUES (5,'和歌山県');
INSERT INTO prefectures (region_id, name) VALUES (6,'鳥取県');
INSERT INTO prefectures (region_id, name) VALUES (6,'島根県');
INSERT INTO prefectures (region_id, name) VALUES (6,'岡山県');
INSERT INTO prefectures (region_id, name) VALUES (6,'広島県');
INSERT INTO prefectures (region_id, name) VALUES (6,'山口県');
INSERT INTO prefectures (region_id, name) VALUES (7,'徳島県');
INSERT INTO prefectures (region_id, name) VALUES (7,'香川県');
INSERT INTO prefectures (region_id, name) VALUES (7,'愛媛県');
INSERT INTO prefectures (region_id, name) VALUES (7,'高知県');
INSERT INTO prefectures (region_id, name) VALUES (8,'福岡県');
INSERT INTO prefectures (region_id, name) VALUES (8,'佐賀県');
INSERT INTO prefectures (region_id, name) VALUES (8,'長崎県');
INSERT INTO prefectures (region_id, name) VALUES (8,'熊本県');
INSERT INTO prefectures (region_id, name) VALUES (8,'大分県');
INSERT INTO prefectures (region_id, name) VALUES (8,'宮崎県');
INSERT INTO prefectures (region_id, name) VALUES (8,'鹿児島県');
INSERT INTO prefectures (region_id, name) VALUES (8,'沖縄県');
