version: '3'
services:
  db:
    image: oracle/database:12.2.0.1-ee
    container_name: oracle
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./oracle/init:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Tokyo
      - ORACLE_SID=ORCL
      - ORACLE_PDB=oracle
      - ORACLE_PWD=Oracle12
      - ORACLE_CHARACTERSET=AL32UTF8
